version: "3.3"
services:

  guacamole:
    # https://guacamole.apache.org/doc/gug/guacamole-docker.html
    image: guacamole/guacamole:1.0.0
#    network_mode: "host"
    ports:
      - 8080:8080
    environment:
      GUACD_HOSTNAME: "guacd"
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      GUACAMOLE_HOME: /guacamole_home
    volumes:
      - ./config/guacamole_home:/guacamole_home

  guacd:
    image: guacamole/guacd:1.0.0
#    network_mode: "host"
    
  postgres:
    image: postgres:11.3-alpine
    environment:
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}

  nginx:
    image: nginx:1.15-alpine
#    network_mode: "host"
    ports:
      - 8000:8000
    volumes:
      - ./config/conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html

