version: "3.3"
services:

  guacamole:
    # https://guacamole.apache.org/doc/gug/guacamole-docker.html
    image: guacamole/guacamole:1.0.0
    ports:
      - 8080:8080
    environment:
      GUACD_HOSTNAME: "guacd"
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  guacd:
    image: guacamole/guacd:1.0.0
    
  postgres:
    image: postgres:11.3-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GUAC_PASSWORD: ${GUAC_PASSWORD}
    volumes:
      - ./config/pg-initialization:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:1.15-alpine
    ports:
      - 443:443
    volumes:
      - ./config/conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
      - /var/lib/acme/live/guac.testingzone.club/fullchain:/var/lib/acme/live/guac.testingzone.club/fullchain
      - /var/lib/acme/live/guac.testingzone.club/privkey:/var/lib/acme/live/guac.testingzone.club/privkey

