version: "3.3"
services:

  guacamole:
    image: guacamole/guacamole:1.0.0
    network_mode: "host"
    environment:
      GUACAMOLE_HOME: "/guacamole-home"
      GUACD_HOSTNAME: "127.0.0.1"
    volumes:
      - ./config:/guacamole-home 

  guacd:
    image: guacamole/guacd:1.0.0
    network_mode: "host"

  nginx:
    image: nginx:1.15-alpine
    network_mode: "host"
    volumes:
      - ./config/conf.d:/etc/nginx/conf.d
      - /var/lib/acme/:/var/lib/acme/
